export const SEARCH = 'blog/search'
export const CATEGORYFILTER = 'blog/categoryfilter'
export const IMAGEFILTER = 'blog/imagefilter'
export const AUTHORNAMEFILTER = 'blog/authornamefilter'
export const AUTHORIMAGEFILTER = 'blog/authorimagefilter'
